[workspace]

members = [
    "part_1_sbot_rocket",
    "part_2_subscribe_form",
    "part_3_database_follows",
    "part_4_posts_streams",
    "part_5_task_loop",
    "part_6_ui_layout",
    "part_7_latest_posts",
    "part_8_ui_posts",
    "part_9_read_delete"
]
