[package]
name = "part_2_subscribe_form"
version = "0.1.0"
edition = "2021"

[dependencies]
golgi = { git = "https://git.coopcloud.tech/golgi-ssb/golgi.git" }
log = "0.4"
rocket = "0.5.0-rc.1"
rocket_dyn_templates = { version = "0.1.0-rc.1", features = ["tera"] }
